### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by amesy** [mtianyan/xadmin_django2.0.1#1]
Hi, 您好, 我发现一个问题： 
widgets.py 文件的第75行，可以用先替换后切片的方法, 不需要if判断，你参考下。 
`input_html = [ht for ht in super(AdminSplitDateTime, self).render(name, value, attrs).replace('/>', '/>,', 1).split(',') if ht != '']`

**Comment by uesrnameisnull** [comment]
wedgets.py 第80行修改如下
修改原因:解决datatime数据类型抛'出list index out of range'异常
```python
input_html = [ht for ht in super(AdminSplitDateTime, self).render(name, value, attrs).split('/><') if ht != '']
input_html[0] = input_html[0] + "/>"
input_html[1] = "<" + input_html[1]
```
